LapShop/Areas/Admin/Controllers/HomeController.cs
using LapShop.Services.Category;
using LapShop.Domains;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly ICategoryService _CategoryService;
        public HomeController(ICategoryService CategoryService)
        {
            _CategoryService = CategoryService;
        }
        public IActionResult Index()
        {
            return View("Index");
        }

        public async Task<IActionResult> Category()
        {
            IEnumerable<Category> Categories = await _CategoryService.PrepareDashboard();
            return View("Category", Categories);
        }
    }
}

LapShop/Controllers/HomeController.cs
using System.Diagnostics;
using LapShop.Services.Item;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IItemService  _itemService;
        public HomeController(ILogger<HomeController> logger, IItemService itemService)
        {
            _logger = logger;
            _itemService = itemService;
        }

        public async Task<IActionResult> Index()
        {
            var list = await _itemService.PrepareHomepage();
            return View(list);
        }
    }
}

LapShop/Controllers/ItemController.cs
using LapShop.Domains.ViewModels;
using LapShop.Services.Item;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemService _itemService;

        public ItemController(IItemService itemService)
        {
            _itemService = itemService;
        }
        public IActionResult Item(int id)
        {
            ItemDetailsVM itemDetails = new ItemDetailsVM
            {
                Item = _itemService.GetSingle(id),
                RelatedProducts = _itemService.PrepareDashboard(null).Select(e => new Domains.Item()
                {
                    ItemId = e.ItemId,
                    ItemName = e.ItemName,
                    SalesPrice = e.SalesPrice,
                    PurchasePrice = e.PurchasePrice,
                    ImageName = e.ImageName,
                    Gpu = e.Gpu,
                    HardDisk = e.HardDisk,
                    Processor = e.Processor,
                    RamSize = e.RamSize,
                }).ToList(),
            };
            return View(itemDetails);
        }
    }
}

LapShop/Controllers/OrderController.cs
using LapShop.Domains.ViewModels;
using LapShop.Services.Order;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Controllers
{
    public class QuantityDTO
    {
        public int ItemId { get; set; }
        public int ItemCount { get; set; }
        public decimal ItemTotalPrice { get; set; }
    }
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public async Task<IActionResult> Cart()
        {
            return View(await _orderService.GetCart());
        }

        public IActionResult AddToCart(int id, int? quantity = null)
        {
            try
            {
                _orderService.AddCart(id, quantity);
                return RedirectToAction("Cart");
            }
            catch (Exception ex)
            {
                return StatusCode(500, "An error occurred while adding the item to the cart: " + ex.Message);
            }
        }

        [HttpPost("ChangeQuantity")]
        public IActionResult ChangeQuantity([FromBody] QuantityDTO quantityDTO)
        {
            try
            {
                var cart = _orderService.GetCart().Result;
                var cartItem = cart.Items.FirstOrDefault(i => i.ItemId == quantityDTO.ItemId);
                
                if (cartItem != null)
                {
                    cartItem.Quantity = quantityDTO.ItemCount;
                    cartItem.TotalPrice = quantityDTO.ItemTotalPrice;
                    cart.TotalPrice = cart.Items.Sum(i => i.TotalPrice);
                }
                _orderService.UpdateCart(cart);
                return Ok(cart);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "An error occurred while changing the quantity: " + ex.Message);
            }
        }

        [HttpPost]
        public IActionResult SaveOrder(ShoppingCartVM cart)
        {
            try
            {
                _orderService.UpdateCart(cart);
                return Ok("Order saved successfully.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, "An error occurred while saving the order: " + ex.Message);
            }
        }


        public async Task<IActionResult> DeleteCartItem(int id)
        {
            try
            {
                var cart = await _orderService.GetCart();
                var cartItem = cart.Items.FirstOrDefault(i => i.ItemId == id);
                
                if (cartItem != null)
                {
                    cart.Items.Remove(cartItem);
                    cart.TotalPrice = cart.Items.Sum(i => i.TotalPrice);
                    _orderService.UpdateCart(cart);
                }
                return RedirectToAction("Cart");
            }
            catch (Exception ex)
            {
                return StatusCode(500, "An error occurred while deleting the item from the cart: " + ex.Message);
            }
        }
    }
}

LapShop/Views/Home/partials/SpecialProductsPartial.cshtml
@model HomepageVM

<!-- Tab product -->
<div class="title1 section-t-space">
	<h4>exclusive products</h4>
	<h2 class="title-inner1">special products</h2>
</div>
<section class="section-b-space p-t-0 ratio_asos">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="theme-tab">
					<ul class="tabs tab-title">
						<li class="current"><a href="tab-4">New Products</a></li>
						<li class=""><a href="tab-5">Featured Products</a></li>
						<li class=""><a href="tab-6">Best Sellers</a></li>
					</ul>
					<div class="tab-content-cls">
						<div id="tab-4" class="tab-content active default">
							<div class="no-slider row">
								@foreach (var item in Model.NewProducts)
								{
									<div class="product-box">
										<div class="img-wrapper">
											<div class="front">
												<div class="card">
													<a asp-controller="Item" asp-action="Item" asp-route-id="@item.ItemId">
														<img src="@item.ImageName"
															 class="card-img-top h-100" alt="">
													</a>
												</div>
											</div>
											<div class="back">
												<div class="card">
													<a asp-controller="Item" asp-action="Item" asp-route-id="@item.ItemId">
														<img src="@item.ImageName"
															 class="card-img-top h-100" alt="">
													</a>
												</div>
											</div>
											<div class="cart-info cart-wrap">
												<a asp-controller="Order" asp-action="AddToCart" asp-route-id="@item.ItemId">
													<i class="ti-shopping-cart"></i>
												</a>
											</div>
										</div>
										<div class="product-detail">
											<div class="rating">
												<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i>
											</div>
											<a href="product-page(no-sidebar).html">
												<h6>@item.ItemName</h6>
											</a>
											<h4>EGP @item.SalesPrice</h4>
										</div>
									</div>
								}
							</div>
						</div>
						<div id="tab-5" class="tab-content">
							<div class="no-slider row">
								@foreach (var item in Model.FeaturedProducts)
								{
									<div class="product-box">
										<div class="img-wrapper">
											<div class="front">
												<div class="card">
													<a asp-controller="Item" asp-action="Item" asp-route-id="@item.ItemId">
														<img src="@item.ImageName"
															 class="card-img-bottom h-100" alt="">
													</a>
												</div>
											</div>
											<div class="back">
												<div class="card">
													<a asp-controller="Item" asp-action="Item" asp-route-id="@item.ItemId">
														<img src="@item.ImageName"
															 class="card-img-bottom h-100" alt="">
													</a>
												</div>
											</div>
											<div class="cart-info cart-wrap">
												<a asp-controller="Order" asp-action="AddToCart" asp-route-id="@item.ItemId">
													<i class="ti-shopping-cart"></i>
												</a>
											</div>
										</div>
										<div class="product-detail">
											<div class="rating">
												<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i>
											</div>
											<a href="product-page(no-sidebar).html">
												<h6>@item.ItemName</h6>
											</a>
											<h4>EGP @item.SalesPrice</h4>
										</div>
									</div>
								}

							</div>
						</div>
						<div id="tab-6" class="tab-content">
							<div class="no-slider row">
								@foreach (var item in Model.BestSellers)
								{
									<div class="product-box">
										<div class="img-wrapper">
											<div class="front">
												<div class="card">
													<a asp-controller="Item" asp-action="Item" asp-route-id="@item.ItemId">
														<img src="@item.ImageName"
															 class="card-img-bottom h-100" alt="">
													</a>
												</div>
											</div>
											<div class="back">
												<div class="card">
													<a asp-controller="Item" asp-action="Item" asp-route-id="@item.ItemId">
														<img src="@item.ImageName"
															 class="card-img-bottom h-100" alt="">
													</a>
												</div>
											</div>
											<div class="cart-info cart-wrap">
												<a asp-controller="Order" asp-action="AddToCart" asp-route-id="@item.ItemId">
													<i class="ti-shopping-cart"></i>
												</a>
											</div>
										</div>
										<div class="product-detail">
											<div class="rating">
												<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i>
											</div>
											<a href="product-page(no-sidebar).html">
												<h6>@item.ItemName</h6>
											</a>
											<h4>EGP @item.SalesPrice</h4>
										</div>
									</div>
								}

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Tab product end -->

LapShop/Views/Home/partials/TopCollectionPartial.cshtml
@model List<Item>
<!-- Paragraph-->
<div class="title1 section-t-space">
	<h4>special offer</h4>
	<h2 class="title-inner1">top collection</h2>
</div>
<div class="container">
	<div class="row">
		<div class="col-lg-6 offset-lg-3">
			<div class="product-para">
				<p class="text-center">
					Lorem Ipsum is simply dummy text of the printing and typesetting industry.
					Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
				</p>
			</div>
		</div>
	</div>
</div>
<!-- Paragraph end -->
<!-- Product slider -->
<section class="section-b-space p-t-0 ratio_asos">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="product-4 product-m no-arrow">
					@foreach (var item in Model)
					{
						<div class="product-box d-flex flex-column justify-content-end">
							<div class="img-wrapper">
								<div class="front">
									<div class="card">
										<a asp-controller="Item" asp-action="Item" asp-route-id="@item.ItemId">
											<img src="@item.ImageName"
												 class="card-img-bottom h-100" alt="no image">
										</a>
									</div>
								</div>
								<div class="back">
									<div class="card h-100">
										<a asp-controller="Item" asp-action="Item" asp-route-id="@item.ItemId">
											<img src="@item.ImageName"
												 class="card-img-bottom h-100" alt="no image">
										</a>
									</div>
								</div>
								<div class="cart-info cart-wrap">
									<a asp-controller="Order" asp-action="AddToCart" asp-route-id="@item.ItemId">
										<i class="ti-shopping-cart"></i>
									</a>
								</div>
							</div>
							<div class="product-detail">
								<div class="rating">
									<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i>
								</div>
								<a href="product-page(no-sidebar).html">
									<h6>@item.ItemName</h6>
								</a>
								<h4>EGP @item.SalesPrice</h4>
							</div>
						</div>
					}
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Product slider end -->