LapShop/Areas/Admin/Controllers/CategoryController.cs
using LapShop.Services.Category;
using LapShop.Domains;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _CategoryService;
        public CategoryController(ICategoryService CatService)
        {
            _CategoryService = CatService;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Category> Categories = await _CategoryService.PrepareDashboard();
            return View("Index", Categories);
        }

        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id is not null)
            {
                return View("Edit", await _CategoryService.GetTargetCategory(Convert.ToInt32(Id)));
            }
            return View("Edit", new Category());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(Category Category, IFormFile File)
        {
            bool IsSuccess = false;
            if (Category.CategoryId == 0)
            {
                Category.ImageName = await Utilities.FileUtility.SaveFile(File, "Images\\Categories", [".jpg", ".jpeg", ".png"]);
                IsSuccess = await _CategoryService.SaveNew(Category);
            }
            else
            {
                // Category Updates may not update images
                if (File is not null)
                {
                    Category.ImageName = await Utilities.FileUtility.SaveFile(File, "Images\\Categories", [".jpg", ".jpeg", ".png"]);
                }
                IsSuccess = await _CategoryService.SaveUpdate(Category);
            }

            if (!IsSuccess)
            {
                return StatusCode(500, "A server side error occured while processing your request");
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            string ImagePath = await _CategoryService.RemoveCategory(id);

            if (ImagePath is null)
            {
                return StatusCode(500, "A server side error occured while processing your request");
            }
            else
            {
                Utilities.FileUtility.DeleteFile(ImagePath);
            }
            return RedirectToAction("Index");
        }
    }
}

LapShop/Areas/Admin/Controllers/PermissionsController.cs
using System.Reflection;
using LapShop.Areas.Admin.Models;
using LapShop.Data;
using LapShop.Services.Permissions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PermissionsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IPermissionsService _permissionsService;

        public PermissionsController(UserManager<ApplicationUser> userManager, IPermissionsService permissionsService)
        {
            _userManager = userManager;
            _permissionsService = permissionsService;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users.ToList());
        }

        public async Task<IActionResult> UserDetails(string userId)
        {
            var asm = Assembly.GetAssembly(typeof(Program));
            var controllerActionGroups = asm?.GetTypes()
                    .Where(type => typeof(Controller).IsAssignableFrom(type))
                    .SelectMany(type => type.GetMethods(BindingFlags.Instance | BindingFlags.DeclaredOnly | BindingFlags.Public))
                    .Where(m => !m.GetCustomAttributes(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute), true).Any())
                    .Select(x => new WebsiteTechnicalData
                    {
                        Area = x.DeclaringType?.GetCustomAttributes(typeof(AreaAttribute), true).FirstOrDefault() is AreaAttribute areaAttr ? areaAttr.RouteValue : "",
                        Controller = x.DeclaringType?.Name ?? string.Empty,
                        Action = x.Name,
                        ReturnType = x.ReturnType.Name,
                        Attributes = string.Join(", ", x.GetCustomAttributes().Select(attr => attr.GetType().Name))
                    })
                    .OrderBy(x => x.Area).ThenBy(x => x.Controller).ThenBy(x => x.Action)
                    .GroupBy(x => x.Area)
                    .Select(g => new AreaGroup
                    {
                        Area = g.Key ?? string.Empty,
                        Controllers = g.GroupBy(x => x.Controller).Select(g => new ControllerActionGroup
                        {
                            Controller = g.Key,
                            TechnicalData = g.ToList()
                                        
                        })
                        .OrderBy(c => c.Controller)
                        .ToList()
                    })
                    .OrderBy(a => a.Area)
                    .ToList();

            UserDetailsVM userDetails = new UserDetailsVM
            {
                UserId = userId,
                AreaGroups = controllerActionGroups,
            };


            List<Domains.UserPermissions> userPermissions = await _permissionsService.GetPermissionsByUser(userId);

            foreach (var areaGroup in userDetails.AreaGroups)
            {
                foreach (var controllerGroup in areaGroup.Controllers)
                {
                    foreach (var action in controllerGroup.TechnicalData)
                    {
                        var permission = userPermissions.FirstOrDefault(up => up.Area == areaGroup.Area && up.Controller == controllerGroup.Controller && up.Action == action.Action);
                        if (permission != null)
                        {
                            action.IsSelected = true;
                            areaGroup.SelectedActions.Add($"{userId}|{areaGroup.Area}|{controllerGroup.Controller}|{action.Action}");
                        }
                    }
                }
            }

            return View(userDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Save(List<string> SelectedActions)
        {
            if (SelectedActions == null || SelectedActions.Count == 0)
            {
                ModelState.AddModelError("", "No actions selected.");
                return RedirectToAction($"Index");
            }

            await _permissionsService.Save(SelectedActions);

            return RedirectToAction("Index");
        }
    }
}

LapShop/Areas/Admin/Controllers/SliderController.cs
using LapShop.Services.Slider;
using LapShop.Domains;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly ISliderService _SliderService;
        public SliderController(ISliderService sliderService)
        {
            _SliderService = sliderService;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Slider> sliders = await _SliderService.PrepareDashboard();
            return View("Index", sliders);
        }

        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id is not null)
            {
                return View("Edit", await _SliderService.GetTargetSlider(Convert.ToInt32(Id)));
            }
            return View("Edit", new Slider());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(Slider Slider, IFormFile File)
        {
            bool IsSuccess = false;
            if (Slider.SliderId == 0)
            {
                string windowsPath = await Utilities.FileUtility.SaveFile(File, "Images\\Sliders", [".jpg", ".jpeg", ".png"]);
                Slider.ImageName = windowsPath.Replace("\\", "/");
                IsSuccess = await _SliderService.SaveNew(Slider);
            }
            else
            {
                // Slider Updates may not update images
                if (File is not null)
                {
                    string windowsPath = await Utilities.FileUtility.SaveFile(File, "Images\\Sliders", [".jpg", ".jpeg", ".png"]);
                    Slider.ImageName = windowsPath.Replace("\\", "/");
                }
                IsSuccess = await _SliderService.SaveUpdate(Slider);
            }

            if (!IsSuccess)
            {
                return StatusCode(500, "A server side error occured while processing your request");
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            string ImagePath = await _SliderService.RemoveSlider(id);

            if (ImagePath is null)
            {
                return StatusCode(500, "A server side error occured while processing your request");
            }
            else
            {
                Utilities.FileUtility.DeleteFile(ImagePath);
            }
            return RedirectToAction("Index");
        }
    }
}

LapShop/Controllers/ItemController.cs
using LapShop.Domains.ViewModels;
using LapShop.Services.Item;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemService _itemService;

        public ItemController(IItemService itemService)
        {
            _itemService = itemService;
        }
        public IActionResult Item(int id)
        {
            ItemDetailsVM itemDetails = new ItemDetailsVM
            {
                Item = _itemService.GetSingle(id),
                RelatedProducts = _itemService.PrepareDashboard(null).Select(e => new Domains.Item()
                {
                    ItemId = e.ItemId,
                    ItemName = e.ItemName,
                    SalesPrice = e.SalesPrice,
                    PurchasePrice = e.PurchasePrice,
                    ImageName = e.ImageName,
                    Gpu = e.Gpu,
                    HardDisk = e.HardDisk,
                    Processor = e.Processor,
                    RamSize = e.RamSize,
                }).ToList(),
            };
            return View(itemDetails);
        }
    }
}

LapShop/Areas/Admin/Views/Shared/_ItemTablePartial.cshtml
@model List<VwItemsVM>

<style>
	#order-listing td, #order-listing th {
		max-width: 150px; /* Adjust as needed */
		overflow: hidden;
		text-overflow: ellipsis; /* Add ellipsis (...) for overflowed text */
		white-space: nowrap; /* Prevent text wrapping */
	}
</style>

<table id="order-listing" class="table no-footer" aria-describedby="order-listing_info">
	<thead>
		<tr>
			<th class="sorting sorting_asc" tabindex="0" aria-controls="order-listing" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Order #: activate to sort column descending" style="width: 107.05px;">@ResAdmin.LblItemName</th>
			<th class="sorting" tabindex="0" aria-controls="order-listing" rowspan="1" colspan="1" aria-label="Purchased On: activate to sort column ascending" style="width: 171.012px;">@ResAdmin.LblSalesPrice</th>
			<th class="sorting" tabindex="0" aria-controls="order-listing" rowspan="1" colspan="1" aria-label="Purchased On: activate to sort column ascending" style="width: 171.012px;">@ResAdmin.LblPurchasePrice</th>
			<th class="sorting" tabindex="0" aria-controls="order-listing" rowspan="1" colspan="1" aria-label="Purchased On: activate to sort column ascending" style="width: 171.012px;">@ResAdmin.LblCategoryName</th>
			<th class="sorting" tabindex="0" aria-controls="order-listing" rowspan="1" colspan="1" aria-label="Purchased On: activate to sort column ascending" style="width: 171.012px;">@ResAdmin.LblItemTypeName</th>
			<th class="sorting" tabindex="0" aria-controls="order-listing" rowspan="1" colspan="1" aria-label="Purchased On: activate to sort column ascending" style="width: 171.012px;">@ResAdmin.LblOperatingSystemName</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var Element in Model)
		{
			<tr class="odd">
				<td class="sorting_1"> @Element.ItemName </td>
				<td> @Element.SalesPrice </td>
				<td> @Element.PurchasePrice </td>
				<td> @Element.CategoryName </td>
				<td> @Element.ItemTypeName </td>
				<td> @Element.OperatingSystemName </td>
				<td>
					<a asp-area="Admin" asp-controller="Item" asp-action="Edit" asp-route-id="@Element.ItemId" class="btn btn-inverse-warning btn-fw">@ResAdmin.LblEdit</a>
				</td>
				<td>
					<a asp-area="Admin" asp-controller="Item" asp-action="Delete" asp-route-id="@Element.ItemId" class="btn btn-inverse-danger btn-fw">@ResAdmin.LblDelete</a>
				</td>
			</tr>
		}
	</tbody>
</table>

LapShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Admin Panel</title>

	<!-- plugins:css -->
	<link rel="stylesheet" href="~/admin/assets/vendors/mdi/css/materialdesignicons.min.css">
	<link rel="stylesheet" href="~/admin/assets/vendors/css/vendor.bundle.base.css">

	<!-- Layout styles -->
	<link rel="stylesheet" href="~/admin/assets/css/demo_3/style.css">

	<link rel="shortcut icon" href="~/admin/assets/images/favicon.png" />

	@await RenderSectionAsync("Styles", required: false)

</head>
<body>
	<div class="container-scroller">
		<div class="horizontal-menu">
			<nav class="bottom-navbar">
				<div class="container">
					<ul class="nav page-navigation">
						<li class="nav-item">
							<a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
								<i class="mdi mdi-home menu-icon"></i>
								<span class="menu-title">Dashboard</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
								<i class="mdi mdi-file-restore menu-icon"></i>
								<span class="menu-title">Category</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="Admin" asp-controller="Item" asp-action="Index">
								<i class="mdi mdi-file-restore menu-icon"></i>
								<span class="menu-title">Items</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="Admin" asp-controller="Slider" asp-action="Index">
								<i class="mdi mdi-file-restore menu-icon"></i>
								<span class="menu-title">Sliders</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="Admin" asp-controller="Permissions" asp-action="Index">
								<i class="mdi mdi-file-restore menu-icon"></i>
								<span class="menu-title">Permissions</span>
							</a>
						</li>
					</ul>
				</div>
			</nav>
		</div>
		@RenderBody()
		<footer class="footer">
			<div class="container">
				<div class="d-sm-flex justify-content-center justify-content-sm-between">
					<span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
					<span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted &amp; made with <i class="mdi mdi-heart text-danger"></i></span>
				</div>
			</div>
		</footer>
	</div>

	<!-- plugins:js -->
	<script src="~/admin/assets/vendors/js/vendor.bundle.base.js"></script>

	<!-- inject:js -->
	<script src="~/admin/assets/js/off-canvas.js"></script>
	<script src="~/admin/assets/js/hoverable-collapse.js"></script>
	<script src="~/admin/assets/js/misc.js"></script>
	<script src="~/admin/assets/js/settings.js"></script>
	<script src="~/admin/assets/js/todolist.js"></script>
	<script src="~/admin/assets/js/jquery.cookie.js"></script>

	<!-- endinject -->
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>